version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
     MYSQL_ROOT_PASSWORD: my-secret-pw -d mysql:tag
    ports:
      - "3306:3306"
    volumes:
      - devdojo_maratona_data:/var/lib/mysql

volumes:
  devdojo_maratona_data:




